runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /send_mail
  script: send_mail.app
  secure: always

- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /(.+)
  static_files: www/\1
  upload: www/(.+)
  secure: always
